### PR TITLE
Finished Part A

### PR DESCRIPTION
**Pull request by shubhamagrawal6629**
Last Review was just finished before the reviewers reviewed so making a new pull request

### CODE REVIEW

**Comment by p-sky** [comment]
Checked the folder structure and make file. The code compiles and runs without issues, the output files are placed in correct folders.

**Comment by cruizm** [comment]
Hello,
Please, do not merge this pull request (PR).
I want to use it as an example during Thursday lecture to explain how to review PR, how to approve them, how to make comments, etc.
As you can see, Peter gave the approval, but he is still with pending reviewers.
Thanks!

**Comment by cruizm** [comment]
Something to consider and something very important every time you make a change in a project, now the folder structure in the README file (and maybe the way the project is compiled and executed) does not match with the current implementation.

**Comment by p-sky** [comment]
Checked that the code compiles, runs and generates output files in correct folders.

**Pull request closed without merging**
